### ISSUE TITLE
Test Epic

### ISSUE THREAD

**Issue by logicalbomb** [getsentry/plugin-hell#37]
Testing to see how epics would look in [tasklist]

```[tasklist]
### Cool things
[ ] Cool thing number 1
[ ] https://github.com/getsentry/team-profiling/issues/27
[ ] Cool thing number 3
```

and not

### Cool things part 2
- [ ] Cool thing number 1
- [ ] https://github.com/getsentry/team-profiling/issues/27
- [ ] Cool thing number 3
